// Mocks generated by Mockito 5.4.6 from annotations
// in tripbybid/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tripbybid/core/error/result.dart' as _i5;
import 'package:tripbybid/core/network/auth_tokens.dart' as _i11;
import 'package:tripbybid/core/usecase/usecase.dart' as _i14;
import 'package:tripbybid/features/auth/data/datasources/auth_local_data_source.dart'
    as _i10;
import 'package:tripbybid/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i8;
import 'package:tripbybid/features/auth/data/models/login_response_model.dart'
    as _i2;
import 'package:tripbybid/features/auth/data/models/user_model.dart' as _i9;
import 'package:tripbybid/features/auth/domain/entities/user.dart' as _i6;
import 'package:tripbybid/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:tripbybid/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i13;
import 'package:tripbybid/features/auth/domain/usecases/login_usecase.dart'
    as _i12;
import 'package:tripbybid/features/auth/domain/usecases/logout_usecase.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseModel_0 extends _i1.SmartFake
    implements _i2.LoginResponseModel {
  _FakeLoginResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Future<_i5.Result<_i6.User>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i5.Result<_i6.User>>.value(
              _i7.dummyValue<_i5.Result<_i6.User>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<_i6.User>>.value(
              _i7.dummyValue<_i5.Result<_i6.User>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.User>>);

  @override
  _i4.Future<_i5.Result<_i6.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i5.Result<_i6.User?>>.value(
              _i7.dummyValue<_i5.Result<_i6.User?>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<_i6.User?>>.value(
              _i7.dummyValue<_i5.Result<_i6.User?>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.User?>>);

  @override
  _i4.Future<_i5.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i8.AuthRemoteDataSource {
  @override
  _i4.Future<_i2.LoginResponseModel> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i2.LoginResponseModel>.value(
              _FakeLoginResponseModel_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.LoginResponseModel>.value(
              _FakeLoginResponseModel_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.LoginResponseModel>);

  @override
  _i4.Future<_i9.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i9.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.UserModel?>.value(),
          )
          as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i10.AuthLocalDataSource {
  @override
  _i4.Future<void> saveSession(_i11.AuthTokens? tokens, _i9.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [tokens, user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasSession() =>
      (super.noSuchMethod(
            Invocation.method(#hasSession, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i9.UserModel?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i4.Future<_i9.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.UserModel?>.value(),
          )
          as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<void> cacheUser(_i9.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i12.LoginUseCase {
  @override
  _i4.Future<_i5.Result<_i6.User>> call(_i12.LoginParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.User>>.value(
              _i7.dummyValue<_i5.Result<_i6.User>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<_i6.User>>.value(
              _i7.dummyValue<_i5.Result<_i6.User>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.User>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i13.GetCurrentUserUseCase {
  @override
  _i4.Future<_i5.Result<_i6.User?>> call(_i14.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<_i6.User?>>.value(
              _i7.dummyValue<_i5.Result<_i6.User?>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<_i6.User?>>.value(
              _i7.dummyValue<_i5.Result<_i6.User?>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.User?>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i15.LogoutUseCase {
  @override
  _i4.Future<_i5.Result<void>> call(_i14.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}
